# -*- coding: utf-8 -*-
"""2_1_Treinamento_modelo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15QRpfavPUDmLtyK-9eULHE5MKmakjv8D

# Treinamento do Modelo

## Divisão Estratificada 70/20/10 por sensor, treinamento do Pipeline

- (SimpleImputer + DecisionTreeRegressor), auditoria de resíduos e exportação do artefato.
- Divisão Temporal Contínua 70/20/10 baseada no sensor de referência (df_target)
para blindagem estrita contra vazamento de dados temporal (Data Leakage).
- Filtrado para sensores 8 a 14, pois são os sensores mais confiáveis e retiramos o target vindo junto
- Necessário carregar a base de dados prata, presente na pasta 1
"""

import os
import sqlite3
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# ==============================================================================
# 1. CARREGAMENTO DAS BASES E FILTRO DOS SENSORES ALVO (08 a 14)
# ==============================================================================
DB_PATH = os.getenv("SQLITE_PRATA_PATH", "tabela_prata_dados_sensores.db")

print(f"[ETAPA 1] Carregando bases da camada Prata de '{DB_PATH}'...")
conn = sqlite3.connect(DB_PATH)
df_leituras = pd.read_sql_query("SELECT * FROM leituras_limpas", conn)
df_target = pd.read_sql_query("SELECT * FROM df_target", conn)
conn.close()

# Conversão estrita para Datetime UTC
df_leituras["reading_time"] = pd.to_datetime(df_leituras["reading_time"], utc=True)
df_target["reading_time"] = pd.to_datetime(df_target["reading_time"], utc=True)

# Alinhamento temporal com o target de referência (Clima_01_EW)
df_target_ref = df_target.rename(columns={"humidity_percent": "target_humidity"})[
    ["reading_time", "target_humidity"]
]
df_dataset_raw = pd.merge(df_leituras, df_target_ref, on="reading_time", how="inner")

# Filtro estrito: apenas os sensores alvos de calibração Floresta_08 a Floresta_14
sensores_alvo = [f"Floresta_{i:02d}" for i in range(8, 15)]
df_dataset = (
    df_dataset_raw[df_dataset_raw["sensor_name"].isin(sensores_alvo)]
    .sort_values("reading_time")
    .reset_index(drop=True)
)

print(f"✓ Sensores selecionados para treino: {sensores_alvo}")
print(f"✓ Amostras totais após filtragem dos nós 08-14: {len(df_dataset):,}")

# ==============================================================================
# 2. MARCADORES TEMPORAIS DO TARGET (70 / 20 / 10) CONTRA DATA LEAKAGE
# ==============================================================================
print("\n[ETAPA 2] Calculando marcos temporais estritos a partir do Target...")

timeline_target = df_target["reading_time"].drop_duplicates().sort_values().reset_index(drop=True)
n_total_target = len(timeline_target)

idx_corte_treino = int(n_total_target * 0.70)
idx_corte_val = int(n_total_target * 0.90)

timestamp_corte_1 = timeline_target.iloc[idx_corte_treino]
timestamp_corte_2 = timeline_target.iloc[idx_corte_val]

print("=" * 80)
print("   MARCADORES TEMPORAIS DE CORTE (BLINDAGEM CONTRA DATA LEAKAGE)")
print("=" * 80)
print(f"Janela de Treino     (70%): de {timeline_target.min()} até {timestamp_corte_1}")
print(f"Janela de Validação  (20%): de {timestamp_corte_1} até {timestamp_corte_2}")
print(f"Janela de Teste      (10%): de {timestamp_corte_2} até {timeline_target.max()}")
print("=" * 80)

# ==============================================================================
# 3. APLICAÇÃO DO CORTE TEMPORAL NOS SENSORES 08 A 14
# ==============================================================================
df_train = df_dataset[df_dataset["reading_time"] < timestamp_corte_1].copy()
df_val = df_dataset[
    (df_dataset["reading_time"] >= timestamp_corte_1) &
    (df_dataset["reading_time"] < timestamp_corte_2)
].copy()
df_test = df_dataset[df_dataset["reading_time"] >= timestamp_corte_2].copy()

# ==============================================================================
# 4. TABELA DE PROPORÇÃO PERCENTUAL E CONTAGEM POR SENSOR
# ==============================================================================
split_audit = []

for sensor in sensores_alvo:
    total_sensor = len(df_dataset[df_dataset["sensor_name"] == sensor])
    n_train = len(df_train[df_train["sensor_name"] == sensor])
    n_val = len(df_val[df_val["sensor_name"] == sensor])
    n_test = len(df_test[df_test["sensor_name"] == sensor])

    split_audit.append({
        "Sensor": sensor,
        "Total": total_sensor,
        "Treino (N)": n_train,
        "Treino (%)": round((n_train / total_sensor) * 100, 1) if total_sensor else 0,
        "Validação (N)": n_val,
        "Validação (%)": round((n_val / total_sensor) * 100, 1) if total_sensor else 0,
        "Teste (N)": n_test,
        "Teste (%)": round((n_test / total_sensor) * 100, 1) if total_sensor else 0
    })

df_split_report = pd.DataFrame(split_audit)

print("\n" + "=" * 90)
print("   DISTRIBUIÇÃO TEMPORAL POR SENSOR (FLORESTA_08 A 14)")
print("=" * 90)
print(df_split_report.to_string(index=False))

total_geral = len(df_dataset)
print("-" * 90)
print(
    f"TOTAL (08-14): {total_geral:,} amostras | "
    f"Treino: {len(df_train):,} ({(len(df_train)/total_geral)*100:.1f}%) | "
    f"Validação: {len(df_val):,} ({(len(df_val)/total_geral)*100:.1f}%) | "
    f"Teste: {len(df_test):,} ({(len(df_test)/total_geral)*100:.1f}%)"
)
print("=" * 90)

# ==============================================================================
# 5. TREINAMENTO DO PIPELINE BEST MODEL
# ==============================================================================
features = ["humidity_percent", "temperature_c", "co2_ppm"]
target_col = "target_humidity"

print(f"\n[ETAPA 3] Ajustando o Pipeline com {len(df_train):,} amostras de treino dos sensores 08 a 14...")

best_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('regressor', DecisionTreeRegressor(
        max_depth=3,
        min_samples_leaf=20,
        random_state=42
    ))
])

best_pipeline.fit(df_train[features], df_train[target_col])
print("✓ Pipeline ajustado com sucesso!")

# Importância Relativa das Features
tree_model = best_pipeline.named_steps['regressor']
df_importance = pd.DataFrame({
    'Feature': features,
    'Importância (%)': (tree_model.feature_importances_ * 100).round(2)
}).sort_values(by='Importância (%)', ascending=False)

print("\n" + "=" * 60)
print("   IMPORTÂNCIA RELATIVA DAS FEATURES (BEST_MODEL)")
print("=" * 60)
print(df_importance.to_string(index=False))

# ==============================================================================
# 6. AUDITORIA DE DESEMPENHO NA VALIDAÇÃO (SENSORES 08 A 14)
# ==============================================================================
df_val_eval = df_val.copy()
df_val_eval['y_pred'] = best_pipeline.predict(df_val[features])

mae_val_raw = mean_absolute_error(df_val_eval[target_col], df_val_eval['humidity_percent'])
mae_val_cal = mean_absolute_error(df_val_eval[target_col], df_val_eval['y_pred'])
rmse_val_cal = np.sqrt(mean_squared_error(df_val_eval[target_col], df_val_eval['y_pred']))
r2_val_cal = r2_score(df_val_eval[target_col], df_val_eval['y_pred'])

print("\n" + "=" * 60)
print("   DESEMPENHO DO MODELO NA JANELA DE VALIDAÇÃO (08 A 14)")
print("=" * 60)
ganho = ((mae_val_raw - mae_val_cal) / mae_val_raw) * 100
print(f"MAE Bruto: {mae_val_raw:.3f}% -> MAE Calibrado: {mae_val_cal:.3f}% (Ganho: {ganho:.2f}%)")
print(f"RMSE Calibrado: {rmse_val_cal:.3f}% | R²: {r2_val_cal:.4f}")

# Tabela individualizada por sensor
sensor_breakdown = []
for sensor in sensores_alvo:
    s_data = df_val_eval[df_val_eval['sensor_name'] == sensor]
    if len(s_data) == 0:
        continue
    s_true = s_data[target_col]
    s_pred = s_data['y_pred']
    s_raw = s_data['humidity_percent']

    sensor_breakdown.append({
        'Sensor': sensor,
        'Leituras': len(s_data),
        'MAE Bruto (%)': mean_absolute_error(s_true, s_raw),
        'MAE Calibrado (%)': mean_absolute_error(s_true, s_pred),
        'RMSE Calibrado (%)': np.sqrt(mean_squared_error(s_true, s_pred)),
        'R²': r2_score(s_true, s_pred)
    })

df_sensor_table = pd.DataFrame(sensor_breakdown).round(3)
print("\n--- Desempenho Individual por Sensor (Validação) ---")
print(df_sensor_table.to_string(index=False))

# ==============================================================================
# 7. GERAÇÃO DE PAINEL GRÁFICO
# ==============================================================================
plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Painel 1: Dispersão Real vs Predito
sns.scatterplot(
    ax=axes[0],
    x=df_val_eval[target_col],
    y=df_val_eval['y_pred'],
    alpha=0.4,
    color='#1f77b4',
    edgecolor='none'
)
min_v = min(df_val_eval[target_col].min(), df_val_eval['y_pred'].min())
max_v = max(df_val_eval[target_col].max(), df_val_eval['y_pred'].max())
axes[0].plot([min_v, max_v], [min_v, max_v], 'r--', lw=2, label='Identidade (1:1)')
axes[0].set_title("1. Calibração: Real vs. Predito (Validação)", fontsize=11, fontweight='bold')
axes[0].set_xlabel("Umidade Real do Sensor de Referência (%)")
axes[0].set_ylabel("Umidade Calibrada pelo Modelo (%)")
axes[0].legend()

# Painel 2: Histograma de Resíduos
residuals = df_val_eval[target_col] - df_val_eval['y_pred']
sns.histplot(ax=axes[1], x=residuals, kde=True, color='#2ca02c', bins=30)
axes[1].axvline(0, color='black', linestyle='--', lw=1.2)
axes[1].set_title("2. Distribuição dos Erros Residuais", fontsize=11, fontweight='bold')
axes[1].set_xlabel("Erro Residual (Real - Predito) em %")
axes[1].set_ylabel("Frequência")

# Painel 3: Importância das Features
sns.barplot(ax=axes[2], data=df_importance, x='Feature', y='Importância (%)', palette='Blues_r')
axes[2].set_title("3. Importância das Features Físicas", fontsize=11, fontweight='bold')
axes[2].set_ylabel("Peso no Modelo (%)")
axes[2].set_ylim(0, 100)
for p in axes[2].patches:
    axes[2].annotate(f"{p.get_height():.1f}%", (p.get_x() + p.get_width() / 2., p.get_height() + 2),
                     ha='center', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
fig_output = "validacao_best_model_figura7.png"
plt.savefig(fig_output, dpi=300)
plt.close()
print(f"\n[INFO] Gráficos exportados com sucesso em '{fig_output}'.")

# ==============================================================================
# 8. EXPORTAÇÃO DO ARTEFATO FINAL
# ==============================================================================
output_filename = "best_model.joblib"
joblib.dump(best_pipeline, output_filename)
file_size_kb = os.path.getsize(output_filename) / 1024
print(f"[SUCESSO] Artefato exportado: '{output_filename}' ({file_size_kb:.2f} KB).")