# -*- coding: utf-8 -*-
"""4_1_auditoria_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z8s9Xy7aiNfoWtLUuw3gF3u34kc1fd-q

# Auditoria de Paridade Determinística:

- Compara a inferência serverless gravada no DynamoDB contra a predição local do best_model.joblib.
"""

!pip install boto3

import os
import getpass
import boto3
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==============================================================================
# 0. FUNÇÕES AUXILIARES DE CONFIGURAÇÃO
# ==============================================================================
def obter_parametro(var_name: str, label: str, default: str = None, is_secret: bool = False) -> str:
    valor = os.getenv(var_name)
    if valor:
        return valor
    prompt = f"Informe {label}" + (f" [{default}]: " if default else ": ")
    if is_secret:
        entrada = getpass.getpass(prompt).strip()
    else:
        entrada = input(prompt).strip()
    return entrada if entrada else (default or "")

# ==============================================================================
# 1. LEITURA DOS DADOS NO DYNAMODB
# ==============================================================================
print("[ETAPA 1] Conectando ao Amazon DynamoDB para auditoria...")

AWS_KEY = obter_parametro("AWS_ACCESS_KEY_ID", "AWS Access Key ID", is_secret=True)
AWS_SECRET = obter_parametro("AWS_SECRET_ACCESS_KEY", "AWS Secret Access Key", is_secret=True)
AWS_REGION = obter_parametro("AWS_DEFAULT_REGION", "Região AWS", default="us-east-1")
TABLE_NAME = obter_parametro("DYNAMO_TABLE_NAME", "Nome da Tabela DynamoDB", default="LeiturasSensoresCalibrados")

dynamodb = boto3.resource(
    "dynamodb",
    region_name=AWS_REGION,
    aws_access_key_id=AWS_KEY,
    aws_secret_access_key=AWS_SECRET
)
table = dynamodb.Table(TABLE_NAME)

print(f"Executando Scan na tabela '{TABLE_NAME}'...")
response = table.scan()
items = response.get("Items", [])
while "LastEvaluatedKey" in response:
    response = table.scan(ExclusiveStartKey=response["LastEvaluatedKey"])
    items.extend(response.get("Items", []))

if not items:
    raise ValueError(f"A tabela '{TABLE_NAME}' não retornou registros para auditoria.")

df_cloud = pd.DataFrame(items)
print(f"✓ Total de registros recuperados do DynamoDB: {len(df_cloud):,}")

# Conversão de tipos (Decimal -> float)
cols_num = ["humidity_raw", "humidity_calibrated", "temperature_c", "co2_ppm", "timestamp_epoch_ms"]
for col in cols_num:
    if col in df_cloud.columns:
        df_cloud[col] = pd.to_numeric(df_cloud[col], errors="coerce")

# ==============================================================================
# 2. REPRODUÇÃO DA INFERÊNCIA LOCAL (LOCAL PIPELINE)
# ==============================================================================
print("\n[ETAPA 2] Executando predição local com o artefato 'best_model.joblib'...")

# Busca o modelo na pasta local ou na pasta de treinamento
MODEL_PATH = "best_model.joblib"
if not os.path.exists(MODEL_PATH):
    MODEL_PATH = os.path.join("..", "2-treinamento_modelo", "best_model.joblib")

if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"Artefato do modelo não localizado em '{MODEL_PATH}'.")

pipeline = joblib.load(MODEL_PATH)

# Features estritas: [humidity_percent, temperature_c, co2_ppm]
X_audit = df_cloud[["humidity_raw", "temperature_c", "co2_ppm"]].rename(
    columns={"humidity_raw": "humidity_percent"}
).values

df_cloud["pred_local"] = pipeline.predict(X_audit)
df_cloud["divergencia_nuvem_local"] = np.abs(df_cloud["humidity_calibrated"] - df_cloud["pred_local"])

# ==============================================================================
# 3. RELATÓRIO DE CONSISTÊNCIA E PARIDADE
# ==============================================================================
sensores_alvo = [f"Floresta_{i:02d}" for i in range(8, 15)]
df_auditoria = df_cloud[df_cloud["sensor_name"].isin(sensores_alvo)].sort_values(
    by=["sensor_name", "timestamp_epoch_ms"]
)

print("\n" + "=" * 90)
print("   RELATÓRIO DE AUDITORIA: DYNAMODB (AWS LAMBDA) VS. PIPELINE LOCAL")
print("=" * 90)
cols_view = ["sensor_name", "reading_time", "humidity_raw", "humidity_calibrated", "pred_local", "divergencia_nuvem_local"]
print(df_auditoria[cols_view].head(15).to_string(index=False))

erro_max = df_auditoria["divergencia_nuvem_local"].max()
print("-" * 90)
print(f"Divergência Máxima Absoluta: {erro_max:.6f}%")

if erro_max < 1e-4:
    print("STATUS: PARIDADE CONFIRMADA (100% determinístico e livre de discrepâncias numéricas).")
else:
    print("STATUS: ALERTA - Discrepância numérica identificada entre nuvem e local.")

# ==============================================================================
# 4. EXPORTAÇÃO GRÁFICA DA AUDITORIA
# ==============================================================================
plt.figure(figsize=(9, 4.5))
plt.scatter(
    df_auditoria["humidity_raw"],
    df_auditoria["humidity_calibrated"],
    color="#1f77b4",
    alpha=0.6,
    edgecolors="k",
    s=40,
    label="Inferência Serverless (AWS Lambda)"
)
min_v = df_auditoria["humidity_raw"].min()
max_v = df_auditoria["humidity_raw"].max()
plt.plot([min_v, max_v], [min_v, max_v], "r--", lw=1.5, label="Leitura Bruta (Identidade)")

plt.title("Auditoria de Produção: Umidade Bruta vs. Calibrada (DynamoDB)", fontsize=11, fontweight="bold")
plt.xlabel("Umidade Bruta do Sensor (%)")
plt.ylabel("Umidade Calibrada Gravada na Nuvem (%)")
plt.legend()
plt.grid(True, linestyle=":", alpha=0.6)
plt.tight_layout()

fig_name = "auditoria_paridade_nuvem.png"
plt.savefig(fig_name, dpi=300)
plt.close()
print(f"\n[INFO] Gráfico salvo com sucesso: '{fig_name}'")