# -*- coding: utf-8 -*-
"""4_2_drift_monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzpqsQ5hcU3zfWv42Q92SaIZQjfm-HNI

# Avaliação de drift

* Modelo rascunho a ser validado com mais dados do sensor

- Avaliação estatística de:
  - Covariate Shift (Data Drift via KS-Test)
  - Degradação de desempenho preditivo (Model Drift via MAE e R²).
"""

import os
import sqlite3
import pandas as pd
import numpy as np
from scipy.stats import ks_2samp
from sklearn.metrics import mean_absolute_error, r2_score

# ==============================================================================
# 1. FUNÇÕES DE MONITORAMENTO
# ==============================================================================
def detectar_data_drift(df_baseline: pd.DataFrame, df_producao: pd.DataFrame, colunas: list, p_valor_corte: float = 0.05) -> pd.DataFrame:
    """
    Aplica o teste bicaudal de Kolmogorov-Smirnov (KS-Test) comparando a distribuição
    da base de treino histórica (baseline) contra os dados coletados em produção.
    """
    relatorio = {}

    for col in colunas:
        amostra_ref = df_baseline[col].dropna().values
        amostra_prod = df_producao[col].dropna().values

        if len(amostra_ref) == 0 or len(amostra_prod) == 0:
            continue

        stat, p_val = ks_2samp(amostra_ref, amostra_prod)
        drift_detectado = bool(p_val < p_valor_corte)

        relatorio[col] = {
            "KS_Statistic": round(stat, 4),
            "p_value": round(p_val, 6),
            "Data_Drift": drift_detectado
        }

    return pd.DataFrame(relatorio).T

def avaliar_model_drift(df_producao: pd.DataFrame, limiar_mae_alerta: float = 4.5) -> dict:
    """
    Compara as predições geradas em produção contra o alvo de referência (ground truth),
    identificando perda de calibração física dos sensores.
    """
    df_validos = df_producao.dropna(subset=["target_humidity", "humidity_calibrated"])

    if len(df_validos) < 5:
        return {"Status": "Amostras com ground truth insuficientes para calcular Model Drift."}

    y_true = df_validos["target_humidity"].astype(float)
    y_pred = df_validos["humidity_calibrated"].astype(float)

    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    return {
        "Amostras_Avaliadas": len(df_validos),
        "MAE_Producao (%)": round(mae, 4),
        "R2_Producao": round(r2, 4),
        "Alerta_Recalibracao": bool(mae > limiar_mae_alerta)
    }

# ==============================================================================
# 2. EXECUÇÃO DE EXEMPLO / AUDITORIA LOCAL
# ==============================================================================
if __name__ == "__main__":
    DB_PATH = os.getenv("SQLITE_PRATA_PATH", "tabela_prata_dados_sensores.db")
    if not os.path.exists(DB_PATH):
        DB_PATH = os.path.join("..", "1-ingestao_simulador", "tabela_prata_dados_sensores.db")

    if os.path.exists(DB_PATH):
        conn = sqlite3.connect(DB_PATH)
        df_prata = pd.read_sql_query("SELECT * FROM leituras_limpas", conn)
        conn.close()

        features = ["humidity_percent", "temperature_c", "co2_ppm"]

        # Simula split temporal baseline (70%) vs produção (30%) para validar o cálculo
        corte = int(len(df_prata) * 0.70)
        df_baseline = df_prata.iloc[:corte]
        df_prod_sim = df_prata.iloc[corte:]

        print("=" * 70)
        print("   RELATÓRIO DE DATA DRIFT (KOLMOGOROV-SMIRNOV TEST)")
        print("=" * 70)
        df_ks_report = detectar_data_drift(df_baseline, df_prod_sim, features)
        print(df_ks_report.to_string())
        print("=" * 70)
    else:
        print(f"[AVISO] Base '{DB_PATH}' não encontrada para execução de teste local de drift.")