# -*- coding: utf-8 -*-
"""4.3-analise_graficos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PByRqsi7285oieIrXYEORtYUQCCTX6fq

# Avaliação visual de desempenho

- Plots de avaliação desse modelo protótipo
"""

import os
import sqlite3
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Configuração visual
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 10,
    "axes.labelsize": 11,
    "axes.titlesize": 11,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "figure.titlesize": 12,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "savefig.bbox": "tight"
})

print("✓ Ambiente configurado para geração de figuras com qualidade de publicação.")

# ==============================================================================
# 2. CARREGAMENTO DOS DADOS (PRATA) E ALINHAMENTO DO GROUND TRUTH
# ==============================================================================
DB_PATH = "tabela_prata_dados_sensores.db"
if not os.path.exists(DB_PATH):
    DB_PATH = os.path.join("..", "1-ingestao_simulador", "tabela_prata_dados_sensores.db")

MODEL_PATH = "best_model.joblib"
if not os.path.exists(MODEL_PATH):
    MODEL_PATH = os.path.join("..", "2-treinamento_modelo", "best_model.joblib")

conn = sqlite3.connect(DB_PATH)
df_leituras = pd.read_sql_query("SELECT * FROM leituras_limpas", conn)
df_target = pd.read_sql_query("SELECT * FROM df_target", conn)
conn.close()

# Tipagem estrita
df_leituras["reading_time"] = pd.to_datetime(df_leituras["reading_time"], utc=True)
df_target["reading_time"] = pd.to_datetime(df_target["reading_time"], utc=True)

# Merge com o sensor padrão de referência (Clima_01_EW)
df_target_ref = df_target.rename(columns={"humidity_percent": "target_humidity"})[
    ["reading_time", "target_humidity"]
]
df_dataset = pd.merge(df_leituras, df_target_ref, on="reading_time", how="inner")

# Filtro estrito dos sensores avaliados
sensores_alvo = [f"Floresta_{i:02d}" for i in range(8, 15)]
df_dataset = df_dataset[df_dataset["sensor_name"].isin(sensores_alvo)].sort_values("reading_time").reset_index(drop=True)

# Execução do modelo campeão
pipeline = joblib.load(MODEL_PATH)
features = ["humidity_percent", "temperature_c", "co2_ppm"]
df_dataset["humidity_calibrated"] = pipeline.predict(df_dataset[features])

print(f"✓ Total de medições sincronizadas carregadas: {len(df_dataset):,}")
print(f"✓ Sensores processados: {sensores_alvo}")

# ==============================================================================
# FIGURA 1: CURVAS TEMPORAIS (SENSOR EXPERIMENTAL VS. CALIBRADO VS. GROUND TRUTH)
# ==============================================================================
sensor_exemplo = "Floresta_12"
df_s = df_dataset[df_dataset["sensor_name"] == sensor_exemplo].sort_values("reading_time").tail(120)

fig, ax = plt.subplots(figsize=(10, 4))

ax.plot(df_s["reading_time"], df_s["target_humidity"], label="Referência de Bancada (Clima_01_EW)", color="black", lw=2, linestyle="-")
ax.plot(df_s["reading_time"], df_s["humidity_percent"], label=f"Leitura Bruta ({sensor_exemplo})", color="#d62728", lw=1.2, linestyle=":")
ax.plot(df_s["reading_time"], df_s["humidity_calibrated"], label="Calibração Serverless (ML)", color="#1f77b4", lw=1.8, linestyle="--")

ax.set_ylabel("Umidade Relativa (%)")
ax.set_xlabel("Horário de Medição (UTC)")
ax.set_title(f"Rastreamento de Dinâmica Temporal: Nó {sensor_exemplo}", fontweight="bold")
ax.grid(True, linestyle=":", alpha=0.6)
ax.legend(frameon=True, facecolor="white", edgecolor="none")

plt.savefig("figura_1_series_temporais.png")
plt.show()

# ==============================================================================
# FIGURA 2: DISPERSÃO COMPARATIVA (ANTES vs. DEPOIS DA CALIBRAÇÃO)
# ==============================================================================
fig, axes = plt.subplots(1, 2, figsize=(11, 4.5), sharey=True, sharex=True)

mae_bruto = mean_absolute_error(df_dataset["target_humidity"], df_dataset["humidity_percent"])
r2_bruto = r2_score(df_dataset["target_humidity"], df_dataset["humidity_percent"])

mae_cal = mean_absolute_error(df_dataset["target_humidity"], df_dataset["humidity_calibrated"])
r2_cal = r2_score(df_dataset["target_humidity"], df_dataset["humidity_calibrated"])

# Subplot 1: Leitura Bruta vs Ground Truth
axes[0].scatter(df_dataset["target_humidity"], df_dataset["humidity_percent"], alpha=0.25, color="#d62728", s=15)
min_val = min(df_dataset["target_humidity"].min(), df_dataset["humidity_percent"].min())
max_val = max(df_dataset["target_humidity"].max(), df_dataset["humidity_percent"].max())
axes[0].plot([min_val, max_val], [min_val, max_val], "k--", lw=1.5, label="Identidade 1:1")
axes[0].set_title(f"(a) Sinal Bruto\nMAE: {mae_bruto:.2f}% | R²: {r2_bruto:.3f}", fontweight="bold")
axes[0].set_xlabel("Umidade Real de Referência (%)")
axes[0].set_ylabel("Medição do Sensor (%)")
axes[0].grid(True, linestyle=":", alpha=0.5)
axes[0].legend(loc="upper left")

# Subplot 2: Leitura Calibrada vs Ground Truth
axes[1].scatter(df_dataset["target_humidity"], df_dataset["humidity_calibrated"], alpha=0.25, color="#1f77b4", s=15)
axes[1].plot([min_val, max_val], [min_val, max_val], "k--", lw=1.5, label="Identidade 1:1")
axes[1].set_title(f"(b) Sinal Calibrado via ML\nMAE: {mae_cal:.2f}% | R²: {r2_cal:.3f}", fontweight="bold")
axes[1].set_xlabel("Umidade Real de Referência (%)")
axes[1].grid(True, linestyle=":", alpha=0.5)
axes[1].legend(loc="upper left")

plt.savefig("figura_2_dispersao_identidade.png")
plt.show()

# ==============================================================================
# FIGURA 3: DISTRIBUIÇÃO E DENSIDADE DOS ERROS RESIDUAIS
# ==============================================================================
erro_bruto = df_dataset["humidity_percent"] - df_dataset["target_humidity"]
erro_calibrado = df_dataset["humidity_calibrated"] - df_dataset["target_humidity"]

fig, ax = plt.subplots(figsize=(8, 4))

sns.kdeplot(erro_bruto, ax=ax, label=f"Resíduos Brutos (Média: {erro_bruto.mean():.2f}%)", color="#d62728", fill=True, alpha=0.2, lw=1.8)
sns.kdeplot(erro_calibrado, ax=ax, label=f"Resíduos Calibrados (Média: {erro_calibrado.mean():.2f}%)", color="#1f77b4", fill=True, alpha=0.2, lw=1.8)

ax.axvline(0, color="black", linestyle="--", lw=1.2, label="Erro Nulo (Ideal)")
ax.set_xlabel("Erro Residual de Umidade: $y_{medido} - y_{real}$ (%)")
ax.set_ylabel("Densidade de Probabilidade")
ax.set_title("Compensação de Bias: Distribuição dos Resíduos", fontweight="bold")
ax.grid(True, linestyle=":", alpha=0.6)
ax.legend()

plt.savefig("figura_3_distribuicao_residuos.png")
plt.show()

# ==============================================================================
# FIGURA 4: BENCHMARK POR NÓ SENSOR (MAE BRUTO VS. MAE CALIBRADO)
# ==============================================================================
metrics_list = []
for sensor in sensores_alvo:
    df_sn = df_dataset[df_dataset["sensor_name"] == sensor]
    m_raw = mean_absolute_error(df_sn["target_humidity"], df_sn["humidity_percent"])
    m_cal = mean_absolute_error(df_sn["target_humidity"], df_sn["humidity_calibrated"])
    metrics_list.append({"Sensor": sensor, "MAE Bruto (%)": m_raw, "MAE Calibrado (%)": m_cal})

df_metrics = pd.DataFrame(metrics_list)

x = np.arange(len(df_metrics))
width = 0.35

fig, ax = plt.subplots(figsize=(9, 4))
rects1 = ax.bar(x - width/2, df_metrics["MAE Bruto (%)"], width, label="Sinal Bruto", color="#d62728", alpha=0.85)
rects2 = ax.bar(x + width/2, df_metrics["MAE Calibrado (%)"], width, label="Após Calibração", color="#1f77b4", alpha=0.85)

ax.set_ylabel("Erro Médio Absoluto - MAE (%)")
ax.set_title("Redução de Erro Sistemático por Nó da Rede IoT", fontweight="bold")
ax.set_xticks(x)
ax.set_xticklabels(df_metrics["Sensor"], rotation=0)
ax.grid(axis="y", linestyle=":", alpha=0.6)
ax.legend()

# Anotação de valores sobre as barras
for rect in rects1 + rects2:
    height = rect.get_height()
    ax.annotate(f"{height:.1f}", xy=(rect.get_x() + rect.get_width() / 2, height),
                xytext=(0, 2), textcoords="offset points", ha="center", va="bottom", fontsize=8)

plt.savefig("figura_4_mae_individual_sensores.png")
plt.show()

# ==============================================================================
# FIGURA 5: MATRIZ DE CORRELAÇÃO DE PEARSON ENTRE PARÂMETROS AMBIENTAIS
# ==============================================================================
cols_corr = ["humidity_percent", "temperature_c", "co2_ppm", "target_humidity"]
labels_corr = ["Umid. Bruta", "Temp. (°C)", "CO2 (ppm)", "Umid. Real"]

corr_matrix = df_dataset[cols_corr].corr()

fig, ax = plt.subplots(figsize=(6, 4.5))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap="vlag",
    vmin=-1,
    vmax=1,
    xticklabels=labels_corr,
    yticklabels=labels_corr,
    ax=ax,
    cbar_kws={"label": "Coeficiente de Pearson"}
)
ax.set_title("Correlação Multivariável no Microclima", fontweight="bold")

plt.savefig("figura_5_correlacao_ambiental.png")
plt.show()