# -*- coding: utf-8 -*-
"""1_1_data_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRPdvFAl_yKHmUUVuNasEPAeKg723BX3

# Programa para adquirir dados da base de sondas e criar bancos locais (Bronze e Prata)
- Credenciais e caminhos de rede não fornecidos: busca em variáveis de ambiente; se ausentes, solicita no terminal.

## Instalar bibliotecas
"""

!pip install sshtunnel paramiko==2.12.0

"""#Programa para adquirir dados da base de sondas e criar bancos locais (Bronze e Prata)
- Credenciais e caminhos de rede: busca em variáveis de ambiente; se ausentes, solicita no terminal.
"""

# ==============================================================================
# 0. AMBIENTE E DEPENDÊNCIAS
# ==============================================================================

import os
import getpass
import sqlite3
import pandas as pd
import psycopg2
from sshtunnel import SSHTunnelForwarder

# ==============================================================================
# 1. CONFIGURAÇÕES E PARÂMETROS
# ==============================================================================
print("[ETAPA 1] Carregando parâmetros de configuração...")

# Função auxiliar para buscar variável de ambiente ou solicitar no terminal interativamente
def obter_parametro(var_name: str, label: str, default: str = None, is_secret: bool = False) -> str:
    # Tenta obter do ambiente
    valor = os.getenv(var_name)
    if valor:
        return valor

    # Se não encontrar no ambiente, solicita entrada interativa no terminal
    prompt = f"Informe {label}" + (f" [{default}]: " if default else ": ")
    if is_secret:
        entrada = getpass.getpass(prompt).strip()
    else:
        entrada = input(prompt).strip()

    return entrada if entrada else (default or "")


# Obter_parametro() para fallback interativo no terminal caso a variável não exista
SSH_HOST = obter_parametro("DB_SSH_HOST", "SSH Host (Bastion)")
SSH_PORT = int(obter_parametro("DB_SSH_PORT", "SSH Port", default="22"))
SSH_USER = obter_parametro("DB_SSH_USER", "SSH Username")
SSH_PASSWORD = obter_parametro("DB_SSH_PASSWORD", "SSH Password", is_secret=True)

REMOTE_HOST = obter_parametro("DB_REMOTE_HOST", "Remote DB Host", default="127.0.0.1")
REMOTE_PORT = int(obter_parametro("DB_REMOTE_PORT", "Remote DB Port", default="5432"))
LOCAL_PORT = int(obter_parametro("DB_LOCAL_PORT", "Local Tunnel Port", default="15432"))

DB_USER = obter_parametro("DB_USER", "PostgreSQL Database User")
DB_PASS = obter_parametro("DB_PASS", "PostgreSQL Database Password", is_secret=True)
DB_NAME = obter_parametro("DB_NAME", "PostgreSQL Database Name", default="painel_de_dados_db")

# Bancos Locais SQLite (Camadas Bronze e Prata)
SQLITE_BRONZE_DB = "tabela_bronze_dados_sensores.db"
SQLITE_PRATA_DB = "tabela_prata_dados_sensores.db"


print("✓ Parâmetros configurados com sucesso.\n")

# ==============================================================================
# 2. EXTRAÇÃO DE DADOS (SSH TUNNEL + POSTGRESQL) -> CAMADA BRONZE
# ==============================================================================
print("[ETAPA 2] Iniciando conexão com o banco de dados remoto...")

try:
    with SSHTunnelForwarder(
        (SSH_HOST, SSH_PORT),
        ssh_username=SSH_USER,
        ssh_password=SSH_PASSWORD,
        remote_bind_address=(REMOTE_HOST, REMOTE_PORT),
        local_bind_address=("127.0.0.1", LOCAL_PORT),
    ) as tunnel:

        print(f"✓ Túnel SSH aberto na porta local: {tunnel.local_bind_port}")
        conn = psycopg2.connect(
            host="127.0.0.1",
            port=tunnel.local_bind_port,
            user=DB_USER,
            password=DB_PASS,
            dbname=DB_NAME,
        )
        print("✓ Conexão PostgreSQL autenticada com sucesso!")

        sql_query = """
        SELECT s.sensor_name, r.reading_time, r.co2_ppm, r.temperature_c, r.humidity_percent, r.absolute_pressure_kpa
        FROM public.sensor_reading r
        JOIN public.sensor s ON s.id = r.sensor_id
        WHERE r.reading_time >= '2026-08-29 00:00:00'
          AND r.reading_time <= '2026-08-30 23:59:59'
        ORDER BY r.reading_time, s.sensor_name;
        """

        print("Executando extração das leituras brutas...")
        df_leituras = pd.read_sql_query(sql_query, conn)
        print(f"✓ Extração concluída! Total de linhas: {len(df_leituras)}")
        conn.close()

    print("✓ Túnel SSH fechado com sucesso.\n")

except Exception as e:
    print(f"✗ Erro na extração remota: {e}")
    raise e

# ==============================================================================
# 3. GRAVAÇÃO DA CAMADA BRONZE (DADOS BRUTOS EM SQLITE)
# ==============================================================================
print(f"[ETAPA 3] Gravando camada Bronze no arquivo '{SQLITE_BRONZE_DB}'...")

try:
    conn_bronze = sqlite3.connect(SQLITE_BRONZE_DB)
    df_bronze_to_save = df_leituras.copy()
    df_bronze_to_save["reading_time"] = df_bronze_to_save["reading_time"].astype(str)

    df_bronze_to_save.to_sql("leituras_sensores", conn_bronze, if_exists="replace", index=False)
    print(f"✓ Camada Bronze salva com sucesso: {len(df_bronze_to_save)} registros.")
    conn_bronze.close()

except Exception as e:
    print(f"✗ Erro ao salvar camada Bronze: {e}")
    raise e

# ==============================================================================
# 4. PROCESSAMENTO E REFINAMENTO -> CAMADA PRATA
# ==============================================================================
print("\n[ETAPA 4] Processando dados para a camada Prata...")

# 4.1 Limpeza inicial de umidade nula
df_leituras_cleaned = df_leituras.dropna(subset=['humidity_percent']).copy()
print(f"✓ Registros após descartar NaNs em 'humidity_percent': {len(df_leituras_cleaned)}")

# Garantir formato datetime UTC
df_leituras_cleaned['reading_time'] = pd.to_datetime(df_leituras_cleaned['reading_time'], utc=True)

# 4.2 Alinhamento temporal com o sensor de referência (Clima_01_EW)
df_sensor_raw = (
    df_leituras_cleaned[df_leituras_cleaned['sensor_name'].astype(str).str.strip() == 'Clima_01_EW']
    .dropna(subset=['humidity_percent'])
    .sort_values('reading_time')
)

min_reading_time = df_sensor_raw['reading_time'].min()
print(f"Ponto de corte temporal inicial (Sensor de Referência): {min_reading_time}")

# Cortar a base original a partir do timestamp inicial do target
df_leituras_cleaned = df_leituras_cleaned[df_leituras_cleaned['reading_time'] >= min_reading_time].copy()

# 4.3 Construção da grade temporal e interpolação do Target
full_timeline = pd.DatetimeIndex(df_leituras_cleaned['reading_time'].drop_duplicates().sort_values())

df_target = (
    df_sensor_raw.drop_duplicates(subset=['reading_time'])
    .set_index('reading_time')
    .reindex(full_timeline)
)

df_target['humidity_percent'] = (
    df_target['humidity_percent']
    .interpolate(method='time')
    .bfill()
    .ffill()
    .astype('float64')
)

df_target['sensor_name'] = 'Clima_01_EW'
df_target = df_target.reset_index().rename(columns={'index': 'reading_time'})
df_target = df_target[['sensor_name', 'reading_time', 'humidity_percent']]

# ==============================================================================
# 5. GRAVAÇÃO DA CAMADA PRATA (SQLITE)
# ==============================================================================
print(f"\n[ETAPA 5] Gravando camada Prata no arquivo '{SQLITE_PRATA_DB}'...")

try:
    conn_prata = sqlite3.connect(SQLITE_PRATA_DB)

    # 5.1 Gravação de leituras_limpas
    df_limpas_save = df_leituras_cleaned.copy()
    df_limpas_save['reading_time'] = df_limpas_save['reading_time'].astype(str)
    df_limpas_save.to_sql("leituras_limpas", conn_prata, if_exists="replace", index=False)
    print(f"✓ Tabela 'leituras_limpas' salva com {len(df_limpas_save)} registros.")

    # 5.2 Gravação de df_target
    df_target_save = df_target.copy()
    df_target_save['humidity_percent'] = pd.to_numeric(df_target_save['humidity_percent'], errors='coerce')
    df_target_save = df_target_save.dropna(subset=['humidity_percent'])
    df_target_save['humidity_percent'] = df_target_save['humidity_percent'].astype(float)
    df_target_save['reading_time'] = df_target_save['reading_time'].astype(str)

    df_target_save.to_sql("df_target", conn_prata, if_exists="replace", index=False)
    print(f"✓ Tabela 'df_target' salva com {len(df_target_save)} registros.")

    conn_prata.close()
    print("✓ Processamento e persistência das camadas concluídos com sucesso!")

except Exception as e:
    print(f"✗ Erro ao salvar camada Prata: {e}")
    raise e