# -*- coding: utf-8 -*-
"""1.2-publisher_iot_https.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1op6jxYH3J8Xqw20fgVz37sCvLDqkJV_7

# Publicador de telemetria em lote via protocolo HTTPS REST (boto3)

- Credenciais e endpoint não fornecidos: busca em variáveis de ambiente; se ausentes, solicita no terminal.

## Instalar dependências
"""

!pip install boto3

import os
import getpass
import json
import sqlite3
import time
from datetime import datetime
import pandas as pd
import boto3

# ==============================================================================
# 0. FUNÇÕES AUXILIARES DE ENTRADA
# ==============================================================================
def obter_parametro(var_name: str, label: str, default: str = None, is_secret: bool = False) -> str:
    # Busca na variável de ambiente correspondente
    valor = os.getenv(var_name)
    if valor:
        return valor

    # Se não encontrado no ambiente, solicita entrada interativa no terminal
    prompt = f"Informe {label}" + (f" [{default}]: " if default else ": ")
    if is_secret:
        entrada = getpass.getpass(prompt).strip()
    else:
        entrada = input(prompt).strip()

    return entrada if entrada else (default or "")

# ==============================================================================
# 1. AUTENTICAÇÃO E CONFIGURAÇÃO AWS
# ==============================================================================
print("[ETAPA 1] Configuração de Acesso ao AWS IoT Core (HTTPS):")


# Parametrização com prioridade para env vars padrão da AWS e fallback interativo
AWS_KEY = obter_parametro("AWS_ACCESS_KEY_ID", "AWS Access Key ID", is_secret=True)
AWS_SECRET = obter_parametro("AWS_SECRET_ACCESS_KEY", "AWS Secret Access Key", is_secret=True)
AWS_REGION = obter_parametro("AWS_DEFAULT_REGION", "Região AWS", default="us-east-1")

# Endpoint parametrizado para não expor identificador da conta na base de código pública
IOT_ENDPOINT = obter_parametro(
    "AWS_IOT_ENDPOINT",
    "Endpoint ATS do AWS IoT Core (ex: https://<id>-ats.iot.<region>.amazonaws.com)",
    default="https://seu-endpoint-ats.iot.us-east-1.amazonaws.com"
)

# Validação do prefixo HTTPS exigido pelo boto3
if not IOT_ENDPOINT.startswith("https://"):
    IOT_ENDPOINT = f"https://{IOT_ENDPOINT}"

iot_client = boto3.client(
    "iot-data",
    region_name=AWS_REGION,
    endpoint_url=IOT_ENDPOINT,
    aws_access_key_id=AWS_KEY,
    aws_secret_access_key=AWS_SECRET
)
print("✓ Cliente AWS IoT Data inicializado com sucesso.\n")

# ==============================================================================
# 2. CARREGAMENTO E PREPARAÇÃO DOS DADOS
# ==============================================================================
print("[ETAPA 2] Carregando e filtrando dados da camada Prata...")

DB_PATH = obter_parametro("SQLITE_PRATA_PATH", "Caminho do banco SQLite Prata", default="tabela_prata_dados_sensores.db")
conn = sqlite3.connect(DB_PATH)

df_limpas = pd.read_sql_query("SELECT * FROM leituras_limpas", conn)

# Tenta carregar o target se existir
try:
    df_target = pd.read_sql_query(
        "SELECT sensor_name, reading_time, humidity_percent as target_humidity FROM df_target",
        conn
    )
    df_merged = pd.merge(df_limpas, df_target, on=["sensor_name", "reading_time"], how="left")
except Exception:
    df_merged = df_limpas
    df_merged["target_humidity"] = None

conn.close()

# Filtra sensores Floresta_08 a Floresta_14
sensores_alvo = [f"Floresta_{i:02d}" for i in range(8, 15)]
df_filtrado = df_merged[df_merged["sensor_name"].isin(sensores_alvo)].copy()

# Pega as 10 últimas leituras de cada sensor
df_batch = (
    df_filtrado.sort_values(by=["sensor_name", "reading_time"])
    .groupby("sensor_name", as_index=False)
    .tail(10)
    .reset_index(drop=True)
)

print(f"✓ Total de leituras selecionadas para envio: {len(df_batch)}\n")

# ==============================================================================
# 3. ENVIO EM LOTE PARA O BROKER (HTTPS REST)
# ==============================================================================
print(f"[ETAPA 3] Publicando mensagens no endpoint {IOT_ENDPOINT}...")
sucessos = 0

for idx, (_, row) in enumerate(df_batch.iterrows(), 1):
    sensor = str(row["sensor_name"])
    rt_str = str(row["reading_time"])

    # Converte ISO string para timestamp epoch ms
    dt = datetime.fromisoformat(rt_str.replace("Z", "+00:00"))
    ts_ms = int(dt.timestamp() * 1000)

    payload = {
        "sensor_name": sensor,
        "reading_time": rt_str,
        "timestamp_epoch_ms": ts_ms,
        "humidity_percent": float(row["humidity_percent"]),
        "temperature_c": float(row["temperature_c"]),
        "co2_ppm": None if pd.isna(row["co2_ppm"]) else float(row["co2_ppm"]),
        "absolute_pressure_kpa": None if pd.isna(row["absolute_pressure_kpa"]) else float(row["absolute_pressure_kpa"]),
        "target_humidity": None if pd.isna(row.get("target_humidity")) else float(row["target_humidity"])
    }

    topic = f"floresta/sensores/{sensor}"
    resp = iot_client.publish(
        topic=topic,
        qos=1,
        payload=json.dumps(payload)
    )

    if resp["ResponseMetadata"]["HTTPStatusCode"] == 200:
        sucessos += 1

    if idx % 10 == 0 or idx == len(df_batch):
        print(f"[{idx}/{len(df_batch)}] Enviado: {sensor} (Timestamp: {ts_ms})")

    time.sleep(0.04)

print(f"\n✓ Envio concluído: {sucessos}/{len(df_batch)} leituras publicadas com sucesso!")