# -*- coding: utf-8 -*-
"""1.3-publisher_iot_mqtt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSmliFW7tqnueeCx7zDsdWZgShI43OVT

# Publicador de telemetria em tempo real via protocolo MQTT nativo (awsiotsdk / WebSockets com SigV4)

- Credenciais e endpoint não fornecidos: busca em variáveis de ambiente; se ausentes, solicita no terminal.

## Instalar dependências
"""

!pip install awsiotsdk

import os
import getpass
import sqlite3
import pandas as pd
import json
import time
from datetime import datetime
from awscrt import io, mqtt, auth
from awsiot import mqtt_connection_builder

# ==============================================================================
# 0. FUNÇÃO AUXILIAR DE ENTRADA E CONFIGURAÇÃO
# ==============================================================================
def obter_parametro(var_name: str, label: str, default: str = None, is_secret: bool = False) -> str:
    # 1. Busca na variável de ambiente do sistema
    valor = os.getenv(var_name)
    if valor:
        return valor

    # 2. Se ausente, solicita interativamente no terminal
    prompt = f"Informe {label}" + (f" [{default}]: " if default else ": ")
    if is_secret:
        entrada = getpass.getpass(prompt).strip()
    else:
        entrada = input(prompt).strip()

    return entrada if entrada else (default or "")

# ==============================================================================
# 1. PARÂMETROS GLOBAIS DE CONEXÃO E BANCO
# ==============================================================================
print("[ETAPA 1] Configuração de Parâmetros e Conexão AWS IoT (MQTT):")



AWS_REGION = obter_parametro("AWS_DEFAULT_REGION", "Região AWS", default="us-east-1")
RAW_ENDPOINT = obter_parametro(
    "AWS_IOT_ENDPOINT",
    "Endpoint ATS do AWS IoT Core (ex: <id>-ats.iot.<region>.amazonaws.com)",
    default="seu-endpoint-ats.iot.us-east-1.amazonaws.com"
)
# Tratamento para garantir que o cliente MQTT não receba o esquema https:// (exigência do SDK awscrt)
IOT_ENDPOINT = RAW_ENDPOINT.replace("https://", "").replace("http://", "").strip("/")

DB_PATH = obter_parametro("SQLITE_PRATA_PATH", "Caminho do banco SQLite Prata", default="tabela_prata_dados_sensores.db")

print(f"✓ Configurações carregadas. Endpoint alvo: {IOT_ENDPOINT}\n")

# ==============================================================================
# 2. CARREGAMENTO DOS DADOS LOCAIS (CAMADA PRATA)
# ==============================================================================
def carregar_dados_lote(db_path: str) -> pd.DataFrame:
    print(f"[ETAPA 2] Lendo dados da camada Prata a partir de '{db_path}'...")
    conn = sqlite3.connect(db_path)
    df_limpas = pd.read_sql_query("SELECT * FROM leituras_limpas", conn)
    try:
        df_target = pd.read_sql_query(
            "SELECT sensor_name, reading_time, humidity_percent as target_humidity FROM df_target",
            conn
        )
        df_merged = pd.merge(df_limpas, df_target, on=["sensor_name", "reading_time"], how="left")
    except Exception:
        df_merged = df_limpas
        df_merged["target_humidity"] = None
    conn.close()

    sensores_alvo = [f"Floresta_{i:02d}" for i in range(8, 15)]
    df_filtrado = df_merged[df_merged["sensor_name"].isin(sensores_alvo)].copy()

    df_lote = (
        df_filtrado.sort_values(by=["sensor_name", "reading_time"])
        .groupby("sensor_name", as_index=False)
        .tail(10)
        .reset_index(drop=True)
    )
    print(f"✓ Total de amostras selecionadas: {len(df_lote)}")
    return df_lote

# ==============================================================================
# 3. CONEXÃO E PUBLICAÇÃO MQTT (COM QOS 1)
# ==============================================================================
def publicar_via_mqtt(df_lote: pd.DataFrame, aws_key: str, aws_secret: str):
    print("\n[ETAPA 3] Inicializando loop de eventos e credenciais SigV4 para MQTT via WebSockets...")
    event_loop_group = io.EventLoopGroup(1)
    host_resolver = io.DefaultHostResolver(event_loop_group)
    client_bootstrap = io.ClientBootstrap(event_loop_group, host_resolver)

    credentials_provider = auth.AwsCredentialsProvider.new_static(
        access_key_id=aws_key,
        secret_access_key=aws_secret
    )

    mqtt_conn = mqtt_connection_builder.websockets_with_default_aws_signing(
        endpoint=IOT_ENDPOINT,
        client_bootstrap=client_bootstrap,
        region=AWS_REGION,
        credentials_provider=credentials_provider,
        client_id="FlorestaGatewaySimulator",
        clean_session=True,
        keep_alive_secs=30
    )

    print(f"Conectando ao broker MQTT em {IOT_ENDPOINT}...")
    connect_future = mqtt_conn.connect()
    connect_future.result()
    print("✓ Conexão MQTT estabelecida com sucesso!")

    sucessos = 0
    for idx, (_, row) in enumerate(df_lote.iterrows(), 1):
        sensor = str(row["sensor_name"])
        rt_str = str(row["reading_time"])

        dt = datetime.fromisoformat(rt_str.replace("Z", "+00:00"))
        ts_ms = int(dt.timestamp() * 1000)

        payload = {
            "sensor_name": sensor,
            "reading_time": rt_str,
            "timestamp_epoch_ms": ts_ms,
            "humidity_percent": float(row["humidity_percent"]),
            "temperature_c": float(row["temperature_c"]),
            "co2_ppm": None if pd.isna(row["co2_ppm"]) else float(row["co2_ppm"]),
            "absolute_pressure_kpa": None if pd.isna(row["absolute_pressure_kpa"]) else float(row["absolute_pressure_kpa"]),
            "target_humidity": None if pd.isna(row.get("target_humidity")) else float(row["target_humidity"])
        }

        topic = f"floresta/sensores/{sensor}"

        publish_future, _ = mqtt_conn.publish(
            topic=topic,
            payload=json.dumps(payload),
            qos=mqtt.QoS.AT_LEAST_ONCE
        )
        publish_future.result()
        sucessos += 1

        if idx % 10 == 0 or idx == len(df_lote):
            print(f"[{idx}/{len(df_lote)}] Publicado via MQTT (QoS 1): {topic} (timestamp: {ts_ms})")
        time.sleep(0.04)

    disconnect_future = mqtt_conn.disconnect()
    disconnect_future.result()
    print(f"\n✓ Disparo MQTT finalizado: {sucessos}/{len(df_lote)} mensagens entregues ao broker com confirmação.")

# ==============================================================================
# 4. ENTRYPOINT
# ==============================================================================
if __name__ == "__main__":

    # Substituição para checar variáveis de ambiente padrão antes de pedir digitação
    key = obter_parametro("AWS_ACCESS_KEY_ID", "AWS Access Key ID", is_secret=True)
    secret = obter_parametro("AWS_SECRET_ACCESS_KEY", "AWS Secret Access Key", is_secret=True)

    dados = carregar_dados_lote(DB_PATH)
    publicar_via_mqtt(dados, key, secret)