# -*- coding: utf-8 -*-
"""lambda_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nBwO52jVxDXN_SyIXiIP1ZNYw4VTK6XC
"""

import json
import boto3
import os
import joblib
import numpy as np
from decimal import Decimal

DYNAMO_TABLE_NAME = "LeiturasSensoresCalibrados"
dynamodb = boto3.resource("dynamodb", region_name="us-east-1")
table = dynamodb.Table(DYNAMO_TABLE_NAME)

# Carregamento do pipeline com fallback de caminhos
pipeline = None
MODEL_NAME = "best_model.joblib"
for path in [MODEL_NAME, f"/var/task/{MODEL_NAME}", f"/tmp/{MODEL_NAME}"]:
    if os.path.exists(path):
        try:
            pipeline = joblib.load(path)
            print(f"Pipeline carregado de: {path}")
            break
        except Exception as e:
            print(f"Erro ao abrir {path}: {e}")

if pipeline is None:
    print(f"Alerta: {MODEL_NAME} nao localizado. Listando /var/task:", os.listdir("/var/task") if os.path.exists("/var/task") else [])

def to_decimal(val):
    if val is None or val == "" or (isinstance(val, float) and np.isnan(val)):
        return None
    try:
        return Decimal(str(round(float(val), 4)))
    except Exception:
        return str(val)

def lambda_handler(event, context):
    sensor_name = str(event.get("sensor_name", "Desconhecido"))
    reading_time = str(event.get("reading_time", ""))
    timestamp_ms = int(event.get("timestamp_epoch_ms", 0))

    raw_humidity = float(event.get("humidity_percent", 0.0))
    temp_c = float(event.get("temperature_c", 0.0))

    co2_val = event.get("co2_ppm")
    co2 = np.nan if (co2_val is None or co2_val == "" or (isinstance(co2_val, float) and np.isnan(co2_val))) else float(co2_val)
    press_kpa = event.get("absolute_pressure_kpa")

    # Inferência com as 3 features exatas esperadas pelo pipeline: [humidity, temp, co2]
    calibrated_humidity = raw_humidity
    if pipeline is not None:
        try:
            X = np.array([[raw_humidity, temp_c, co2]], dtype=float)
            pred = pipeline.predict(X)
            calibrated_humidity = float(pred[0])
            print(f"Predicao concluida [{sensor_name}]: Bruta={raw_humidity:.2f}% -> Calibrada={calibrated_humidity:.2f}%")
        except Exception as e:
            print(f"Erro na predicao: {e}")

    # Montagem e escrita direta no DynamoDB
    item = {
        "sensor_name": sensor_name,
        "timestamp_epoch_ms": timestamp_ms,
        "reading_time": reading_time,
        "humidity_raw": to_decimal(raw_humidity),
        "humidity_calibrated": to_decimal(calibrated_humidity),
        "temperature_c": to_decimal(temp_c),
        "co2_ppm": to_decimal(co2),
        "absolute_pressure_kpa": to_decimal(press_kpa)
    }

    if "target_humidity" in event and event["target_humidity"] is not None:
        item["target_humidity"] = to_decimal(event["target_humidity"])

    table.put_item(Item=item)
    return {"statusCode": 200, "sensor": sensor_name, "calibrated": calibrated_humidity}